export const images = {
    Back: require('../../Images/Back.png'),
    bari: require('../../Images/bari.png'),
    Logo: require('../../Images/Logo.png'),
    bart: require('../../Images/bart.png'),
    barth: require('../../Images/barth.png'),
    iphone: require('../../Images/iphone.png'),
    google: require('../../Images/google.png'),
    facebook: require('../../Images/facebook.png'),
    // man: require('../../Images/man.png'),
    barcimg: require('../../Images/barcimg.png'),
    cheers: require('../../Images/cheers.png'),
    eye: require('../../Images/eye.png'),
    eyeoff: require('../../Images/eye-off.png'),
    filter: require('../../Images/filter.png'),
    Search: require('../../Images/Search.png'),
    Vector: require('../../Images/Vector.png'),
    homebar: require('../../Images/homebar.png'),
    close: require('../../Images/close.png'),
    home: require('../../Images/home.png'),
    homered: require('../../Images/homered.png'),
    sett: require('../../Images/sett.png'),
    settred: require('../../Images/settred.png'),
    closesr: require('../../Images/closesr.png'),
    detailbar: require('../../Images/detailbar.png'),
    Save: require('../../Images/Save.png'),
    pclose: require('../../Images/pclose.png'),
    pers: require('../../Images/pers.png'),
    heart: require('../../Images/heart.png'),
    noti: require('../../Images/noti.png'),
    faq: require('../../Images/faq.png'),
    feedback: require('../../Images/feedback.png'),
    seeting: require('../../Images/seeting.png'),
    Logout: require('../../Images/Logout.png'),
    goBack: require('../../Images/goBack.png'),
    edit:require('../../Images/edit.png'),
    dil:require('../../Images/dil.png'),
    bartwo:require('../../Images/bartwo.png'),
    hide:require('../../Images/hide.png'),
    setimg:require('../../Images/setimg.png'),
    HomeRedsvg:require('../../Images/HomeRedsvg.png'),
    setredimg:require('../../Images/setredimg.png'),
    glassproeye:require('../../Images/glassproeye.png'),
    colseeyeglasspro:require('../../Images/colseeyeglasspro.png'),
    grayhome:require('../../Images/grayhome.png'),
    filtermenu:require('../../Images/filtermenu.png'),
    heartfild:require('../../Images/heartfild.png'),
    hertlineimg:require('../../Images/hertlineimg.png'),
    magnifying:require('../../Images/magnifying.png'),
    check:require('../../Images/check.png'),
    mannn:require('../../Images/mannn.png'),

    

}