export const String = {
    Allyourfavourites: 'All your favourites',
    onbord: 'Love get together and having a good time? Join us as we introduce you amazing bars and clubs to visit.',
    onbordtwo: 'With over more than 50 places, you will be spoilt for choices.',
    Next: 'Next',
    Getstarted: 'Get started',
    Skip: 'Skip',
    Welcome:'Welcome back',
    Email:'Email',
    Password:'Password',
    Remember:'Remember me',
    ForgotPassword:'Forgot Password',
    LogIn:'Log In',
    Dont:'Don’t have an account?',
    SUBMIT:'SUBMIT',
    ForgetPassword:'Forget Password',
    reset:'A reset password link has been sent to you email.',
    BACKTOLOGIN:'BACK TO LOGIN',
    SignUp:'Sign Up',
    Name:'Name',
    Email:'Email',
    MobileNumber:'Mobile Number',
    ReType:'Re-Type Password',
    DOB:'Date of Birth',
    AllCategories:'All Categories',
    BrowseAll:'Browse All',
    stam: '2 Stamford Road, #70-02 Swissôtel The Stamford, S178882',
    maecenas:'Maecenas sed diam eget risus varius blandit sitamt non magna. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.',
    Beer:'Beer',
    Whisky:"Whisky",
    Wine:"Wine",
    Gin:'Gin',
    Vodka:'Vodka',
    Cocktail:'Cocktail',
    ContactDetails:"Contact Details",
    MrPerryTan:'Mr. Perry Tan',
    perryskaibacom:'perry@skaibar.com',
    numbrr:'+ 65 9200 1234',
    reservati:'www.reservationlink.com',
    Promotions:'Promotions',
    Reservation:"Reservation",
    Reservation:'Reservation',
    please:'Please be informed that reservation will only be confirmed if the companies calls or emails you for the confirmation.',
    enterPax:'Enter N.o of Pax',
    entername:'Enter name',
    enentervalidemail:'Enter valid email',
    entervalidmobile:'Enter valid mobile number',
    ofPax:'N.o of Pax*',
    enterremark:'Enter remark',
    Remarks:"Remarks",
    enterremark:'Enter remark',
    PromoReference:'Promo Reference'

    



   
}